# Generated by Django 5.0.6 on 2024-06-12 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место действия')),
                ('at_action', models.DateTimeField(verbose_name='Время действия')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('is_nice_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье'), ('every day', 'Каждый день')], max_length=15, verbose_name='Периодичность действия')),
                ('reward', models.CharField(max_length=100, verbose_name='Вознаграждение')),
                ('time_to_complete', models.TimeField(verbose_name='Время на выполнение действия')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_habits', to='habitApp.habit', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец привычки')),
            ],
        ),
    ]
