# Generated by Django 5.0.6 on 2024-06-14 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(help_text='укажите действие', max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='associated_habit',
            field=models.ForeignKey(blank=True, help_text='укажите ID приятной привычки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_habits', to='habitApp.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='at_action',
            field=models.DateTimeField(help_text='укажите в какое время выполнять действие', verbose_name='Время действия'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_nice_habit',
            field=models.BooleanField(default=False, help_text='отметьте привычку если она относится к приятным привычкам', verbose_name='Признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, help_text='отметьте если хотите сделать привычку публичной', verbose_name='Признак публичности'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье'), ('daily', 'Каждый день')], default='daily', help_text='выберете периодичность', max_length=15, verbose_name='Периодичность действия'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(help_text='Укажите место выполнение действия', max_length=100, verbose_name='Место действия'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(help_text='укажите вознаграждение', max_length=100, verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.TimeField(help_text='укажите сколько понадобится времени на выполнение действия (максимальное время 2 минуты)', verbose_name='Время на выполнение действия'),
        ),
    ]
