# Generated by Django 5.0.6 on 2024-06-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitApp', '0004_alter_habit_at_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, help_text='укажите вознаграждение', max_length=100, null=True, verbose_name='Вознаграждение'),
        ),
    ]
